language: node_js
node_js:
- node
before_deploy:
- npm run build
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  api_key:
    secure: OYmetuX6vR8tIEI+DtGVhV5FKlsLlut3zWYM1C/M36tVG+d7k5jq6a+WC86EiKdTeYLEL3KJOdsrIUtIDFDhJ9ynIqcuXK5H5si9eSxVr+v9OAC/OuSetuX9ceYp6em1RjQkjkBZzZpNZBGs1PRkHMPj+BTWqmAqNjx7hyjOp2/7HMqG0Ip2LV6cyEOK0AVbUQSvwcZfzqq07bd1BO5V7uuWdaXr+1al+AHdJMDa87M1u3AC9T7J/khs1R7umeMQTa3nHioInQDzxQ/qAy1JMhY24ViiK2HjDwBmQGS8PCv6Xc8MpMV9KOHLuNEAGsRIVsiMRxL5bc6Sl+nzydxPdmzECWvvEGMxgxFeaY5XViwy6gQh9NCc0bzclz0+cnqFC4GS547pnmlQq1LMSQvuFkP/3wM2XRF5+oTm32L1pvcc3CFM/K2OsmHkSRYjsTSZjKt0ey92ZGPFTIqkWCPX5PdmplRpaIReTM5rRD24tbsKBH4+ry+NLK5EQGXoDNysQEbcgFvZ38beknYPLuCBnIrddUpLygGb81gLMaOP7IP3KLO+OfrDW5ECt3aPXKIsArHfxX0Ml4TE6qruXvJVO2ZnbgMue4+7qtycbXi3ElFxrQ0YHKfyivUTxlLzW3RkYgm43uT2jjyY5qCYEL2xKXjngx7YoHkMGwzvXeaUw2k=
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
